### ISSUE TITLE
From releases.md to CHANGELOG.md

### ISSUE THREAD

**Issue by filippodebortoli** [phillord/horned-owl#114]
Not a big change, but it could help to adopt a standard name for the document where we log changes between versions, especially now that the project is starting to grow faster and larger.
It could also be worth adopting some norms about the communication of changes, something like [Common Changelog](https://common-changelog.org/) or [Keep a Changelog](https://keepachangelog.com/en/1.0.0/).

**Comment by phillord** [comment]
I think that "releases.md" as it stands is not a changelog, so this is not a rename. It's something new we would add and would be more detailed.

I'm a little unconvinced by adding a changelog. They are nice but a lot of work and it is not clear that it is going to add much over a git log.
