### ISSUE TITLE
Binary OWL

### ISSUE THREAD

**Issue by areleu** [phillord/horned-owl#116]
I was thinking that there are some cases where I think it would be useful to provide a single file application that contains a full ontology in its binary distribution. This is just speculative but I can imagine delivering an ontology within a WASM binary that uses this API to do some funky visualizations on a browser. 

I guess this would make sense for those ontologies that are not that big. 

I am just putting my toes in the topic and came across https://ceur-ws.org/Vol-1080/owled2013_12.pdf where they say that they implemented it for the OWL API but I can't seem to find this anywhere. 

Do you all see realistic use cases of this feature, if so, how complex would an implementation of a binary serializer/deserializer for this API be?

**Comment by phillord-ncl** [comment]
Supporting a single file binary distribution of an ontology sounds like a perfectly good idea; but I am rather unconvinced by the binary-owl paper. It's not the clearest specification to me, but it would also require a significant amount of effort to implement. Especially compared to a XML/RDF in a zip file -- a simple implementation with all the files at top level  would be a few lines of code; something a bit more general, perhaps with a mapping table in the zip metadata, that would let you put the XML files anywhere in the zip directory structure would be a little more.

Someone most have done this before, I would have thought. XML in a zip file is much wider than OWL.

**Comment by phillord** [comment]
Think I will close this. The paper isn't rich enough and I suspect that no one is likely to find time to do it!
