### ISSUE TITLE
ObjectPropertyChain variant has the wrong type

### ISSUE THREAD

**Issue by althonos** [phillord/horned-owl#14]
Current type of `SubObjectPropertyExpression::ObjectPropertyChain` is:
```rust
enum SubObjectPropertyExpression {
    ObjectPropertyChain(Vec<ObjectProperty>)
    ObjectPropertyExpression(ObjectPropertyExpression)
}
```
or the [functional grammar](https://www.w3.org/TR/owl2-syntax/#Object_Subproperties) production rule for this node is:
```
SubObjectPropertyOf := 'SubObjectPropertyOf' '(' axiomAnnotations subObjectPropertyExpression superObjectPropertyExpression ')'
subObjectPropertyExpression := ObjectPropertyExpression | propertyExpressionChain
propertyExpressionChain := 'ObjectPropertyChain' '(' ObjectPropertyExpression ObjectPropertyExpression { ObjectPropertyExpression } ')'
superObjectPropertyExpression := ObjectPropertyExpression
```

Hence, the right signature in Rust should be
```rust
ObjectPropertyChain(Vec<ObjectPropertyExpression>)
```
(to allow inverse properties in property chains).

**Comment by phillord** [comment]
Yes, this is true. Alas, it makes using the library more complicated again, since there is yet another thing to pull apart. 

I don't suppose waiting to see if anyone in the history of the universe has ever used this construct before we support it is an option? Failing that, I guess adding an `as_property` method to `ObjectPropertyExpression` returning `Option<ObjectProperty>` might help to reduce the baggage a little. WDYT?

**Comment by althonos** [comment]
> Yes, this is true. Alas, it makes using the library more complicated again, since there is yet another thing to pull apart. I don't suppose waiting to see if anyone in the history of the universe has ever used this construct before we support it is an option?

My direct opinion about this is that if this is cumbersome to use but nobody uses it anyway, we might as well get it right from the get go! I don't think there is that much to change in the code anyway, and the `as_property` method seems like a good idea.

I guess you could see something in the wild like
```
SubObjectPropertyOf(
    ObjectProperty("is_nephew")
    ObjectPropertyChain(InverseObjectProperty(ObjectProperty("is_son")), ObjectProperty("is_brother")
)
```
although of course it looks like the least practical construct ever.

**Comment by phillord** [comment]
Yes, I knew you were going to say that.

https://github.com/phillord/horned-owl/compare/fix/subproperty-chain-expressions

WDYT?

**Comment by althonos** [comment]
Looks good to me!
