### ISSUE TITLE
At least two class expressions not enforced

### ISSUE THREAD

**Issue by phillord** [phillord/horned-owl#16]
There are a number of places where the spec requires at least two class expressions (for example, `DisjointUnion` but horned allows any number.

The only solution I can think of is to use `Class, Class, Vec<Class>` as a compound type. This is fairly long winded. It could be made nicer with an `iterator` or a wrapper `Vec2+` object.

https://github.com/phillord/horned-owl/commit/a3b70846b67a22b7b5a32ddb8046538dd1c982dd

**Comment by phillord** [comment]
https://github.com/phillord/at-collection/blob/master/src/lib.rs

Is this a good thing to add or not?

**Comment by phillord** [comment]
Here is my first implementation of this.

https://github.com/phillord/horned-owl/tree/feature/at-least-two

It works, but adds a little to the code base. That can be improved if I macro out the at-collection library, I think.

Hmm, still not sure this is worth it.

**Comment by althonos** [comment]
The issue is going to be with enums, since there is no way to have proper constructors with error-chaining in the different fields. In terms of design, I think the [`syn`](https://docs.rs/syn) crate would be a good inspiration as their AST uses a mix of enums and structs (basically to emulate variant constructors). This could be a way to avoid relying on typing here, and simply check the length of some arguments at runtime instead. But this would also lead to a very large amount of changes in the code so we'd have to discuss that further and/or write proper macros to support the refactor.

**Comment by phillord** [comment]
Not sure I understand the enum issue.

For sure, this cannot all be done by types -- there has to be a runtime check at some point. I've add that ability into `at-collection`, and at `atl2!` macro. So, we would construct like so:

    # use horned_owl::model::*;
    use at_collection::atl2;
    use std::convert::TryFrom;
    // EquivalentClasses(Vec<ClassExpression>)
    let b = Build::new();
    let ec = EquivalentClasses
              (atl2![b.class("http://www.example.com/op1").into(),
                     b.class("http://www.example.com/op2").into()]?);

which is just a switch of `vec!` to `atl2!` and an additional `?` at the end.

The problem is that horned has been written to give relatively direct access to the underlying fields; a deliberate decision really, but one which makes these constraints difficult to enforce without switching to a different type from `Vec`.

I'll finish off the branch and then we can see. I am still worried that this is making the library harder to use, but it might be worth it for the correctness.

**Comment by phillord** [comment]
I know have what I think is a (nearly) complete set of constraints for this added.

https://github.com/phillord/horned-owl/tree/feature/at-least-two

I need to fix some of my sample code (family.owl which has broken `SameIndividual`'s in), so I can restore this test. I guess this shows the utility of adding the constraints.

The "nearly" bit is `DataSome/AllValuesFrom`. I'm talking with Matt and Ignazio about this; it's not clear that the `AtLeastOne` constraint (rather than exactly one) needs supporting or not.

**Comment by phillord** [comment]
I think the ship has sailed on this one and will assume that this API has is is fine. We can address the issue outside of the type system if need be.
