### ISSUE TITLE
DataSomeValuesFrom and DataAllValuesFrom should support data property chaining

### ISSUE THREAD

**Issue by althonos** [phillord/horned-owl#17]
Once again, the grammar show support for 
```
DataSomeValuesFrom := 'DataSomeValuesFrom' '(' DataPropertyExpression { DataPropertyExpression } DataRange ')'

DataAllValuesFrom := 'DataAllValuesFrom' '(' DataPropertyExpression { DataPropertyExpression } DataRange ')'
```

So the enum variants should store `Vec<DataProperty>` instead of `DataProperty`.

**Comment by phillord** [comment]
We should fix this, following the spec, but I don't want to change the API for 1.0. If we ever find an example where someone has used this, we can update for a later release.
