### ISSUE TITLE
ObjectHasSelf should allow ObjectPropertyExpression

### ISSUE THREAD

**Issue by althonos** [phillord/horned-owl#18]
`ObjectHasSelf` is defined in the grammar:
```
ObjectHasSelf := 'ObjectHasSelf' '(' ObjectPropertyExpression ')'
```

but in the code it is only `ObjectHasSelf(ObjectProperty)`.

(Also, it feels weird that this one is the only other tuple variant with `Class` while all the other are structs variants, it's not that elegant to mix both styles IMO).

**Comment by phillord** [comment]
Hopefully, I have fixed this now (the test for ObjectHasSelf was balked anyway, so have found out something useful). Will discuss the "also" in the other issue, since it's another issue:-)
