### ISSUE TITLE
RDF writer does not output any axiom

### ISSUE THREAD

**Issue by althonos** [phillord/horned-owl#37]
It seems like the code for writing the RDF triples containing the OWL axioms is actually commented out, I don't know if this is because it's WIP, or because of a typo.

https://github.com/phillord/horned-owl/blob/ce17ccdc0dc826a34eb17f6d06c7e109c00b9e8a/src/io/rdf/writer.rs#L41-L43

**Comment by phillord** [comment]
It does actually do this though, right? I think this is debug code from the past. We don't use println! for writing to file.

**Comment by althonos** [comment]
Oh, actually I tracked the issue back into my code, there was a weird case of an `unwrap` causing the generating code not to output any error so it would just write an empty RDF element, but with an `expect` it crashed as expected..... This can be closed safely, sorry!
