### ISSUE TITLE
`horned_owl::model::Ontology.mut_doc_iri` does not return a mutable reference

### ISSUE THREAD

**Issue by althonos** [phillord/horned-owl#38]
In the current trait definition for `Ontology`, there's no way to get a mutable reference to the doc IRI:
```rust
pub trait Ontology {
    fn id(&self) -> &OntologyID;
    fn mut_id(&mut self) -> &mut OntologyID;
    fn doc_iri(&self) -> &Option<IRI>;
    fn mut_doc_iri(&mut self) -> &Option<IRI>;
}
```

`mut_doc_iri` signature should be changed to return a mutable reference.

**Comment by phillord** [comment]
Hmmm. Hard not to see this one as a bug really. Can't think of any reason why I did it.
