### ISSUE TITLE
anonymous subclass not parsed in RDF/XML

### ISSUE THREAD

**Issue by balhoff** [phillord/horned-owl#43]
The attached files contain an axiom `(bearer_of some mononucleate) SubClassOf (has_part some nucleus)`.

If I load the OWL/XML file, this axiom is found in the loaded ontology, but if I load the RDF/XML file, it is not. I'm using horned-owl 0.11.0, using:

```
horned_owl::command::parse_path(Path::new("ontology.owx"))
```

[ontologies.zip](https://github.com/phillord/horned-owl/files/8995030/ontologies.zip)

**Comment by phillord** [comment]
Joy. Another edge case which uncovers another three or four edge cases that I have also missed! Sometimes I hate OWL.

This should fix the specific example you have sent, but I need to do all the others that I have written test cases for yet before I merge.

And this shall be the last fix before the next version! Thanks for reporting.
