### ISSUE TITLE
RFC: supporting SWRL Rules

### ISSUE THREAD

**Issue by phillord** [phillord/horned-owl#45]
I have put an initial document up considering how to support SWRL rules. This might also impact on the handling of `OntologyID`.

Work in progress at the moment, so I can't vouch for it's comprehensibility.

https://github.com/phillord/horned-owl/blob/rfc/swrl_rules_redesign.md

**Comment by phillord** [comment]
@jannahastings @althonos @ignazio1977 @jamesaoverton Comments welcome

**Comment by jannahastings** [comment]
For Solution 4, you could still have access methods that gave access to just the OWL axioms vs. the SWRL "axioms", right? I would imagine that many users would only want the OWL parts, but it would be really nice to have the SWRL parts there and accessible when wanted for completeness, without having to use a different type of ontology as the core data structure.

**Comment by phillord** [comment]
@jannahastings Yes, for both three and four that would be possible -- a `filter` and a `filter_map` respectively.  I would be hopeful that it could be done using default methods so all ontology implementations would get them. As you say, for someone using the ontology, the SWRL rules should be ignorable as possible.

**Comment by balhoff** [comment]
I would prefer to just have SWRL rules be a kind of axiom, since I'm familiar with that in the OWL API. When we port the SWRL reasoner over from whelk-scala to whelk-rs (https://github.com/INCATools/whelk-rs/issues/8, hopefully in the next few months) we will need SWRL rule support.

**Comment by phillord** [comment]
Come to the same conclusion.

https://github.com/phillord/horned-owl/pull/59

Haven't actually started on it yet. The spec for SWRL rules is a little more opaque than OWL2, but I think this is next on the list.
