### ISSUE TITLE
Parsing RDF/XML nested declared entities

### ISSUE THREAD

**Issue by filippodebortoli** [phillord/horned-owl#52]
Hi,
a few days ago I tested `horned-summary` to see how it would work.
Out of chance, I chose an ontology that gave `horned` quite the panicking headache.
This is the [Basic Formal Ontology (BFO)](https://raw.githubusercontent.com/BFO-ontology/BFO/releases/1.1.1/bfo.owl) and, after enough fiddling, I found out that the issue lied within `rio` ([issue](https://github.com/oxigraph/rio/issues/110)) and the way it parsed declared entities. The fix has then been integrated in version 0.8.0 of `rio` ([release](https://github.com/oxigraph/rio/releases/tag/v0.8.0)).
All happy, I went ahead and tried to bump the dependency on `horned` and found out (after additional fiddling) that `pretty_rdf` would need to be updated as well ([PR](https://github.com/phillord/pretty_rdf/pull/1) here).
Once that PR gets accepted, I would be happy to open a PR here with the dependency bump.

**Comment by rhinoman** [comment]
Having a similar issue with the current version (0.14).  I could read in [BFO-2020](https://github.com/BFO-ontology/BFO-2020/tree/master/src) in RDF format, but trying to use the RDF writer on it would result in a panic (the OWX Writer still works).

**Comment by filippodebortoli** [comment]
> Having a similar issue with the current version (0.14). I could read in [BFO-2020](https://github.com/BFO-ontology/BFO-2020/tree/master/src) in RDF format, but trying to use the RDF writer on it would result in a panic (the OWX Writer still works).

Hi @rhinoman, would you be able to provide some details regarding the panic? The RDF writer contains a few `unwrap()`s but also some "planned" panics that could help us understand what the issue is in your case.

**Comment by rhinoman** [comment]
@filippodebortoli:
```
PanicException: called `Result::unwrap()` on an `Err` value: ValidityError("No bnode available", Unknown)
```

I'm using py-horned-owl (to which I've added a rust function to write an ontology to an RDF string).  My function does work with other ontologies, but not with BFO-2020.

**Comment by rhinoman** [comment]
This may be unrelated to the issue of parsing.  I did build horned-owl w/ pretty-rdf 0.6.0 and the issue persisted.

**Comment by phillord** [comment]
@rhinoman I have just tried the devel trunk. horned-parse runs on bfo-core.owl without panic. Could you give this a test and see if you can reproduce?

devel is a significant way ahead of main and the last release; my hope is that we can merge devel and release this as 1.0 fairly soon, so it would be good to know if you are still seeing an error.

**Comment by phillord** [comment]
Apologies for the API changes, but at least we have the parsing working now!
