### ISSUE TITLE
horned with no options panics

### ISSUE THREAD

**Issue by phillord** [phillord/horned-owl#54]
It should print the help out

~/src/rust/horned-owl/main/horned-bin$ horned
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', horned-bin/src/bin/horned.rs:38:11
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by filippodebortoli** [comment]
I opened PR #55 that should be fixing this issue.

**Comment by filippodebortoli** [comment]
Fixed by #55.
