### ISSUE TITLE
Intended way of removing components

### ISSUE THREAD

**Issue by areleu** [phillord/horned-owl#79]
Sorry, I think this is more of an advice request than an issue, do you have some discussion board for this kind of questions? 

For context: I am trying to remodel a DL ontology into RL. And I found no proper way of doing it with Robot so I opted to do it with this API. The general idea is to use robot to validate the profile and use the report to build a script with some heuristic on what to do in each case. ( If there is some better approach please enlighten me). 

Now with that clarified, I was wondering what is the "proper" way of modifying an existing ontology. Should I modify the working Mutable ontology or is it cleaner to just create a parallel ontology that is being filled according to some rules. If the ontology is to be mutated, how can I borrow the RcComponentMappedOntology in a way that it can be mutated iteratively? ( I tried making it mutable but if i call "into_iter" or "i" borrows the ontology so I can't change it which makes sense, probably I'm missing something on how to use the indexed ontology.

Here is my code, and the idea is to implement the heuristic in each of the match cases:

```rust
use horned_owl::io::{owx::reader, ParserConfiguration};
use horned_owl::model::*;
use horned_owl::ontology::component_mapped::RcComponentMappedOntology;
use std::fs::File;
use std::io::BufReader;

fn main() {
    let ontology_path: &str = "ontology.owx";
    let file = File::open(&ontology_path).unwrap();
    let mut bufreader = BufReader::new(file);
    let (ont, _) = reader::read(&mut bufreader, ParserConfiguration::default()).unwrap();

    let amo: RcComponentMappedOntology = ont.into();

    for c in amo.into_iter() {
        match &c.component {
            Component::TransitiveObjectProperty(top) => (),
            Component::InverseFunctionalObjectProperty(ifop) => (),
            Component::SubClassOf(SubClassOf { sup, sub }) => {
                match sup {
                    ClassExpression::ObjectAllValuesFrom{ope: a, bce: b} => (),
                    _ => ()
                };
            },
            Component::ObjectPropertyDomain(ObjectPropertyDomain{ope: op, ce: cc}) => {
                match cc {
                    ClassExpression::ObjectUnionOf(vc) => println!("{:?}", vc),
                    _ => ()
                };
            },
            _ => (),
        }
    }
}

```

**Comment by filippodebortoli** [comment]
Hi, by taking a look at what `ontology::component_mapped` offers, my suggestion would be to create an empty mutable ontology `target`, iterate through `amo` as you currently do, use `target.insert(cmp)` whenever the component you are inspecting fits your requirements and then return the mutable ontology.

A slightly different approach could be to define `RLOntologyFilter(ComponentMappedOntology)` and then implement `Visit<A:ForIRI>` for it, where you only need to implement those methods where you want the visitor to actually populate the ontology (see the `visitor` module).

Please, feel free to ask more questions. :-)

**Comment by phillord** [comment]
I think that the easiest way to do this would be just to turn the ontology into iterator and take what you want.

Another possibility might be to create an `RLOntologyIndex`, which would mean you could get a "RL" view on an ontology at any point. But I don't remember my OWL profiles well enough to know how hard that would be. IIRC, the profiles are not purely structural -- they contain global constraints also. That would be a pain to check as you are going.

As you can tell, I haven't really thought about profiles yet. Horned could do with support for moving between and checking profiles.

**Comment by areleu** [comment]
Thanks for the suggestions. RL profiles do indeed have structural constraints, so relying on views alone may be insufficient. That's why I wanted to create a heuristic in the first place.

I opted for the Visit approach and its working but I have to polish the edges. From what I learned I got inspired to begin the implementation of this small library for rendering visualizations: https://github.com/Eugenio2192/barred-owl

Thanks!

**Comment by phillord** [comment]
That looks interesting. How are you going to be doing the visualisation?

**Comment by areleu** [comment]
> That looks interesting. How are you going to be doing the visualisation?

I think I will create dot files first and then move on to other targets. The end goal would be something interactive like some tools like Stardog offer in their platforms, but it's more of a learning-by-doing project so it may take some time to get there.

There is no tool for working with all the features of Graphviz in Rust. There are many different ones that cover useful aspects, but none is "complete" so I'm still trying to use that.

**Comment by filippodebortoli** [comment]
> > That looks interesting. How are you going to be doing the visualisation?
> 
> I think I will create dot files first and then move on to other targets. The end goal would be something interactive like some tools like Stardog offer in their platforms, but it's more of a learning-by-doing project so it may take some time to get there.
> 
> There is no tool for working with all the features of Graphviz in Rust. There are many different ones that cover useful aspects, but none is "complete" so I'm still trying to use that.

There have been past projects aiming at ontology visualization, the one I know is presented in [this paper](https://www.semantic-web-journal.net/system/files/swj1114.pdf). Perhaps it can help w.r.t. design choices.

There is a system called Evonne that visualizes proofs of entailment from a given ontology, while it maybe goes beyond your goal it could provide ideas on which frameworks are used for visualization (IIRC they used Javascript with D3).

In any case, I hope you manage to create a useful tool for your projects! :-)
