### ISSUE TITLE
Standardize formatting and introduce git hooks

### ISSUE THREAD

**Issue by phillord** [phillord/horned-owl#89]
The code base is currently a patchwork of formatting. 

We should standardize on the use of cargo fmt, enforced with git hooks.

**Comment by filippodebortoli** [comment]
Would it be sufficient to have `.git/hooks/pre-commit` to contain the following?

```bash
#!/bin/sh

# Stash unstaged changes (optional but recommended)
git stash -q --keep-index

# Run the linter on staged files
cargo fmt # Replace with the appropriate linting command
RUSTFMT_RESULT=$?

# Unstash the stashed changes (optional but recommended)
git stash pop -q

# Exit with the linter's exit code
exit $RUSTFMT_RESULT
```

(adapted from [this](https://kinsta.com/blog/git-hooks/) blog post).

**Comment by phillord** [comment]
To be honest, I think I am going to use pre-commit.com which looks nice enough.

Currently my own pre-commit checks for uncommited files and runs tests.

In terms of formatting, I would use cargo fmt -- my preference is to check only in pre-commit and break if formatting needs to happen. I think we need to consider clippy also.

The plan would be to add pre-commit first, then add each one of these in their own commits with no other substantive semantic changes. I should have done this a long time ago, but if we are going to do largescale white space, all in one is the way to go.

**Comment by phillord** [comment]
This is now complete and merged. There is a "contribute.md" guide which describes how to install the hooks locally. I am running most of these in github workflow as well, so the same checks should get applied somewhere!
