### ISSUE TITLE
Implement additional traits for all `MutableOntology` implementors

### ISSUE THREAD

**Issue by althonos** [phillord/horned-owl#90]
Consider implementing [std](https://doc.rust-lang.org/std/index.html)::[iter](https://doc.rust-lang.org/std/iter/index.html)::[Extend](https://doc.rust-lang.org/std/iter/trait.Extend.html#) and [std](https://doc.rust-lang.org/std/index.html)::[iter](https://doc.rust-lang.org/std/iter/index.html)::[FromIterator](https://doc.rust-lang.org/std/iter/trait.FromIterator.html#) for all mutable ontologies.

**Comment by phillord** [comment]
Yes, this makes sense; while `FromIterator` can be simulated with `From<SetOntology>`, `Extend` cannot not be.

I will have a fiddle -- we should be able to do this with some generic cleverness over the `OntologyIndex` trait, I think.
